"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";

interface Report {
  id: string;
  title: string;
  periodStart: string;
  periodEnd: string;
  createdAt: string;
  generatedBy: { name: string; email: string };
  contentJson: {
    narrative: string;
    stats: {
      totalItems: number;
      sentimentBreakdown: { POSITIVE: number; NEUTRAL: number; NEGATIVE: number };
      topThemes: { name: string; count: number; sentiment: string }[];
      notableQuotes: string[];
      delta: { positive: number; neutral: number; negative: number };
    };
  };
}

export default function ReportDetailPage() {
  const { id } = useParams() as { id: string };
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`/api/reports/${id}`)
      .then((r) => r.json())
      .then(setReport)
      .finally(() => setLoading(false));
  }, [id]);

  function handlePrint() {
    window.print();
  }

  if (loading) {
    return (
      <div className="p-8 animate-pulse space-y-4">
        <div className="h-8 bg-gray-200 rounded w-64" />
        <div className="h-4 bg-gray-200 rounded w-48" />
        <div className="space-y-2 mt-6">
          {[1, 2, 3, 4, 5].map((i) => <div key={i} className="h-4 bg-gray-200 rounded" />)}
        </div>
      </div>
    );
  }

  if (!report) return <div className="p-8 text-gray-500">Report not found.</div>;

  const stats = report.contentJson?.stats;

  return (
    <div className="p-8 max-w-4xl mx-auto">
      {/* Header */}
      <div className="flex items-start justify-between mb-8 print:mb-4">
        <div>
          <Link href="/reports" className="text-xs text-gray-400 hover:text-gray-600 print:hidden">
            ← Reports
          </Link>
          <h1 className="text-2xl font-bold text-gray-900 mt-1">{report.title}</h1>
          <p className="text-gray-500 text-sm mt-1">
            {new Date(report.periodStart).toLocaleDateString("en-US", { month: "long", day: "numeric" })}
            {" — "}
            {new Date(report.periodEnd).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
          </p>
          <p className="text-xs text-gray-400 mt-1">
            Generated by {report.generatedBy.name} · {new Date(report.createdAt).toLocaleDateString()}
          </p>
        </div>
        <button onClick={handlePrint} className="btn-secondary print:hidden">
          🖨️ Print / Export
        </button>
      </div>

      {/* Stats summary */}
      {stats && (
        <div className="grid grid-cols-3 gap-4 mb-8">
          <div className="card p-4 text-center">
            <p className="text-3xl font-bold text-gray-900">{stats.totalItems}</p>
            <p className="text-xs text-gray-400 mt-1">Feedback items</p>
          </div>
          <div className="card p-4 text-center">
            <p className="text-3xl font-bold text-green-600">
              {stats.sentimentBreakdown?.POSITIVE ?? 0}
            </p>
            <p className="text-xs text-gray-400 mt-1">Positive</p>
            {stats.delta?.positive !== 0 && (
              <p className={`text-xs font-medium ${stats.delta?.positive > 0 ? "text-green-500" : "text-red-500"}`}>
                {stats.delta?.positive > 0 ? "+" : ""}{stats.delta?.positive}pp
              </p>
            )}
          </div>
          <div className="card p-4 text-center">
            <p className="text-3xl font-bold text-red-500">
              {stats.sentimentBreakdown?.NEGATIVE ?? 0}
            </p>
            <p className="text-xs text-gray-400 mt-1">Negative</p>
            {stats.delta?.negative !== 0 && (
              <p className={`text-xs font-medium ${stats.delta?.negative < 0 ? "text-green-500" : "text-red-500"}`}>
                {stats.delta?.negative > 0 ? "+" : ""}{stats.delta?.negative}pp
              </p>
            )}
          </div>
        </div>
      )}

      {/* Narrative */}
      <div className="card p-8 mb-6">
        <div
          className="prose prose-sm max-w-none text-gray-800 leading-relaxed whitespace-pre-wrap"
          style={{ fontFamily: "inherit" }}
        >
          {report.contentJson.narrative}
        </div>
      </div>

      {/* Top themes */}
      {stats?.topThemes?.length > 0 && (
        <div className="card p-6 mb-6">
          <h2 className="text-base font-semibold text-gray-900 mb-4">Top Themes</h2>
          <div className="space-y-2">
            {stats.topThemes.map((t) => (
              <div key={t.name} className="flex items-center justify-between py-2 border-b border-gray-50 last:border-0">
                <span className="text-sm font-medium text-gray-700">{t.name}</span>
                <div className="flex items-center gap-3">
                  <span className="text-xs text-gray-400">{t.sentiment}</span>
                  <span className="text-sm font-semibold text-gray-900">{t.count}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Notable quotes */}
      {stats?.notableQuotes?.length > 0 && (
        <div className="card p-6">
          <h2 className="text-base font-semibold text-gray-900 mb-4">Notable Quotes</h2>
          <div className="space-y-3">
            {stats.notableQuotes.map((q, i) => (
              <blockquote key={i} className="border-l-4 border-indigo-200 pl-4 py-1">
                <p className="text-sm text-gray-600 italic">&ldquo;{q}&rdquo;</p>
              </blockquote>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
